export const ORDERS = [
  {
    id: '#ORD-8821',
    customer: 'Priya Sharma',
    initials: 'PS',
    avatarClass: '',
    date: '19 May 2026',
    items: 3,
    amount: 5499,
    payment: 'UPI',
    status: 'delivered',
  },
  {
    id: '#ORD-8820',
    customer: 'Rahul Mehta',
    initials: 'RM',
    avatarClass: 'av2',
    date: '19 May 2026',
    items: 1,
    amount: 1299,
    payment: 'Card',
    status: 'shipped',
  },
  {
    id: '#ORD-8819',
    customer: 'Anjali Nair',
    initials: 'AN',
    avatarClass: 'av3',
    date: '18 May 2026',
    items: 5,
    amount: 8750,
    payment: 'Netbanking',
    status: 'processing',
  },
  {
    id: '#ORD-8818',
    customer: 'Vikram Singh',
    initials: 'VS',
    avatarClass: 'av4',
    date: '18 May 2026',
    items: 2,
    amount: 2100,
    payment: 'UPI',
    status: 'pending',
  },
  {
    id: '#ORD-8817',
    customer: 'Deepa Krishnan',
    initials: 'DK',
    avatarClass: 'av5',
    date: '17 May 2026',
    items: 4,
    amount: 6200,
    payment: 'COD',
    status: 'delivered',
  },
  {
    id: '#ORD-8816',
    customer: 'Amit Joshi',
    initials: 'AJ',
    avatarClass: 'av6',
    date: '17 May 2026',
    items: 1,
    amount: 899,
    payment: 'Card',
    status: 'cancelled',
  },
  {
    id: '#ORD-8815',
    customer: 'Sneha Pillai',
    initials: 'SP',
    avatarClass: 'av2',
    date: '16 May 2026',
    items: 2,
    amount: 3400,
    payment: 'UPI',
    status: 'refunded',
  },
  {
    id: '#ORD-8814',
    customer: 'Karan Patel',
    initials: 'KP',
    avatarClass: 'av3',
    date: '16 May 2026',
    items: 6,
    amount: 12600,
    payment: 'Card',
    status: 'delivered',
  },
  {
    id: '#ORD-8813',
    customer: 'Meera Reddy',
    initials: 'MR',
    avatarClass: '',
    date: '15 May 2026',
    items: 3,
    amount: 4150,
    payment: 'UPI',
    status: 'shipped',
  },
  {
    id: '#ORD-8812',
    customer: 'Suresh Kumar',
    initials: 'SK',
    avatarClass: 'av4',
    date: '15 May 2026',
    items: 1,
    amount: 750,
    payment: 'COD',
    status: 'processing',
  },
  {
    id: '#ORD-8811',
    customer: 'Nandita Das',
    initials: 'ND',
    avatarClass: 'av5',
    date: '14 May 2026',
    items: 2,
    amount: 2990,
    payment: 'Netbanking',
    status: 'pending',
  },
  {
    id: '#ORD-8810',
    customer: 'Rohan Gupta',
    initials: 'RG',
    avatarClass: 'av6',
    date: '14 May 2026',
    items: 4,
    amount: 7340,
    payment: 'UPI',
    status: 'delivered',
  },
]

export const STATUS_LABELS = {
  delivered: 'Delivered',
  shipped: 'Shipped',
  processing: 'Processing',
  cancelled: 'Cancelled',
  refunded: 'Refunded',
  pending: 'Pending',
}

export const STATUS_COUNTS = {
  all: 1284,
  pending: 38,
  processing: 72,
  shipped: 156,
  delivered: 1006,
  cancelled: 14,
}

export const TABS = [
  { key: 'all', label: 'All' },
  { key: 'pending', label: 'Pending' },
  { key: 'processing', label: 'Processing' },
  { key: 'shipped', label: 'Shipped' },
  { key: 'delivered', label: 'Delivered' },
  { key: 'cancelled', label: 'Cancelled' },
]

export const formatAmount = (amount) =>
  `₹${amount.toLocaleString('en-IN')}`