export const STITCH_TYPES = ['Semi-Stitched', 'Unstitched']
export const PACK_SIZES = ['1', '2', '3']
export const WEIGHTS = ['Light (<500g)', 'Medium (500g-800g)', 'Heavy (>800g)']
export const LENGTH_TYPES = ['Full Length', 'Ankle Length']
export const LINING_OPTIONS = ['Yes', 'No']
export const PRODUCT_TYPES = ['Ready Made', 'Semi-Stitched', 'Unstitched']
export const TOP_LENGTHS = ['Crop', 'Regular', 'Longline', 'Tunic Length', 'Knee Length', 'Calf Length']
export const DUPATTA_SIZES = ['2.25 m', '2.5 m', '2.75 m']
