export const COLOR_MAP = {
  'black':        '#1a1a1a',
  'white':        '#ffffff',
  'off white':    '#f5f0e8',
  'beige':        '#d4b896',
  'grey':         '#9e9e9e',
  'navy blue':    '#1a237e',
  'brown':        '#6d4c41',
  'red':          '#e53935',
  'maroon':       '#7b1a1a',
  'wine':         '#6a1a2e',
  'pink':         '#f48fb1',
  'fuchsia':      '#e040fb',
  'peach':        '#ffcba4',
  'rose':         '#f06292',
  'sky blue':     '#81d4fa',
  'royal blue':   '#1565c0',
  'teal':         '#00897b',
  'turquoise':    '#26c6da',
  'denim blue':   '#3a6186',
  'green':        '#43a047',
  'olive':        '#827717',
  'mint':         '#a5d6a7',
  'emerald':      '#00897b',
  'bottle green': '#1b5e20',
  'yellow':       '#fdd835',
  'mustard':      '#f9a825',
  'golden':       '#ffc107',
  'orange':       '#fb8c00',
  'rust':         '#bf360c',
  'purple':       '#8e24aa',
  'lavender':     '#ce93d8',
  'lilac':        '#b39ddb',
  'plum':         '#6a1b9a',
  'violet':       '#5e35b1',
  'pastel pink':  '#f8bbd0',
  'baby blue':    '#bbdefb',
  'blue':         '#2196f3',
  'gold':         '#d4af37',
  'multicolor':   null,
  'printed':      null,
  'floral':       null,
  'striped':      null,
  'checked':      null,
}

// shared formatter
export const formatColorLabel = (key) =>
  key.replace(/\b\w/g, (c) => c.toUpperCase())