import AdminNav from './AdminNav'

// ponytail: static file, no fetch — generated by e2e/gen_cases.py
// (pytest --collect-only) and written to public/e2e-cases.html; this page
// just frames it, same pattern as TestReports.
export default function TestCases() {
  return (
    <div className='min-h-screen bg-stone-950 text-stone-100'>
      <AdminNav />
      <div className='max-w-7xl mx-auto px-6 py-8 space-y-4'>
        <div>
          <h1 className='text-lg font-bold text-stone-100'>Test Cases</h1>
          <p className='text-xs text-stone-500'>
            Every e2e case, grouped by feature. Static file — refresh after re-running the suite.
          </p>
        </div>
        <div className='bg-white rounded-2xl overflow-hidden border border-stone-800' style={{ height: '80vh' }}>
          <iframe
            src='/e2e-cases.html'
            title='E2E test cases'
            className='w-full h-full border-0'
          />
        </div>
      </div>
    </div>
  )
}
