export const AUTH_URL = import.meta.env.VITE_AUTH_URL ?? ''
export const ORDERS_URL = import.meta.env.VITE_ORDERS_URL ?? ''
export const CATALOG_URL = import.meta.env.VITE_CATALOG_URL ?? ''
export const INVENTORY_URL = import.meta.env.VITE_INVENTORY_URL ?? ''
export const PAYMENT_URL = import.meta.env.VITE_PAYMENT_URL ?? ''
